title: Sparkle CSS Framework
email: philip@heysparkbox.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sparkbox.github.io/sparkle/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SparkleCSS
github_username:  sparkbox

# Build settings

collections_dir: docs
collections:
  setup:
    output: true
    permalink: /setup-:name
  systems:
    output: true
    permalink: /system-:name
  mixins:
    output: true
    permalink: /mixin-:name
  functions:
    output: true
    permalink: /function-:name

sass:
  sass_dir: /_scss
  style: compact

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - docker-compose.yml/
  - gemfiles/
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
